/**
 * Icon shim — maps the app's historical icon names onto lucide-react so every
 * existing `import { XIcon } from "./icons"` call site keeps working unchanged.
 * lucide icons accept `size`, `className`, `strokeWidth`, etc.
 */
export {
  Bot as BotIcon,
  Sparkles as SparklesIcon,
  BookOpen as BookIcon,
  BarChart3 as ChartIcon,
  FileCode as FileIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  LogOut as LogOutIcon,
  Command as CommandIcon,
  Plus as PlusIcon,
  Folder as FolderIcon,
  Layers as LayersIcon,
  Search as SearchIcon,
  ArrowUp as ArrowUpIcon,
  Square as StopIcon,
  Activity as ActivityIcon,
  X as XIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Wrench as WrenchIcon,
  Trash2 as TrashIcon,
  User as UserIcon,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  Bold as BoldIcon,
  Italic as ItalicIcon,
  Code as CodeIcon,
  SquareCode as CodeBlockIcon,
  Link as LinkIcon,
  List as ListIcon,
  Quote as QuoteIcon,
  Eye as EyeIcon,
  Wand2 as WandIcon,
  Library as LibraryIcon,
  Info as InfoIcon,
  Cpu as ChipIcon,
  Globe as GlobeIcon,
  Clock as ClockIcon,
  Share2 as ShareIcon,
  Shield as ShieldIcon,
  Check as CheckIcon,
  Bell as BellIcon,
  Pencil as PencilIcon,
  Columns3 as ColumnsIcon,
  MessageSquare as MessageIcon,
  Copy as CopyIcon,
  Menu as MenuIcon,
  Bookmark as BookmarkIcon,
  Mic as MicIcon,
  MoreHorizontal as MoreIcon,
  Paperclip as PaperclipIcon,
  Volume2 as SpeakerIcon,
  PencilLine as EditIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Archive as ArchiveIcon,
  FileText as FileTextIcon,
} from "lucide-react";
