import DOMPurify from "dompurify";
import hljs from "highlight.js/lib/common";
import katex from "katex";
import { marked } from "marked";

marked.setOptions({ breaks: true, gfm: true });

// Render TeX math to trusted HTML, swapping each match for a placeholder so it
// survives markdown parsing + sanitization; re-inserted verbatim afterwards.
// Supports $$…$$, \[…\] (display) and $…$, \(…\) (inline). Digit-adjacent $ is
// left alone so "$5 and $10" isn't mistaken for math.
function protectMath(text: string, store: string[]): string {
  const tex = (src: string, display: boolean): string => {
    try {
      const html = katex.renderToString(src.trim(), { displayMode: display, throwOnError: false, output: "html" });
      store.push(html);
      return `@@MATH${store.length - 1}@@`;
    } catch {
      return display ? `$$${src}$$` : `$${src}$`;
    }
  };
  return text
    .replace(/\$\$([\s\S]+?)\$\$/g, (_m, s) => tex(s, true))
    .replace(/\\\[([\s\S]+?)\\\]/g, (_m, s) => tex(s, true))
    .replace(/\\\(([\s\S]+?)\\\)/g, (_m, s) => tex(s, false))
    .replace(/(?<![\w$])\$(?!\s)([^$\n]+?)(?<!\s)\$(?![\w$])/g, (_m, s) => tex(s, false));
}

const SPARK =
  '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" ' +
  'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
  '<path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .962 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.962 0z"/></svg>';

function renderPart(text: string): string {
  const math: string[] = [];
  const protectedText = protectMath(text, math);
  const html = marked.parse(protectedText, { async: false }) as string;
  const clean = DOMPurify.sanitize(html, { USE_PROFILES: { html: true }, ADD_ATTR: ["target", "rel"] });
  // Re-insert the trusted KaTeX HTML (generated by us, not user input).
  return math.length ? clean.replace(/@@MATH(\d+)@@/g, (_m, i) => math[Number(i)] ?? "") : clean;
}

// Split <think>…</think> reasoning into collapsible sections; unclosed → open.
export function renderMarkdown(text: string): string {
  const parts: string[] = [];
  let rest = text;
  while (true) {
    const start = rest.indexOf("<think>");
    if (start === -1) {
      if (rest) parts.push(renderPart(rest));
      break;
    }
    if (start > 0) parts.push(renderPart(rest.slice(0, start)));
    const end = rest.indexOf("</think>", start);
    if (end === -1) {
      parts.push(thinkBlock(rest.slice(start + 7), true));
      break;
    }
    parts.push(thinkBlock(rest.slice(start + 7, end), false));
    rest = rest.slice(end + 8);
  }
  return parts.join("");
}

function thinkBlock(inner: string, open: boolean): string {
  const label = open ? "Thinking…" : "Thought process";
  return (
    `<details class="think-block"${open ? " open" : ""}>` +
    `<summary>${SPARK} ${label}</summary>` +
    `<div class="think-content">${renderPart(inner.trim())}</div></details>`
  );
}

// Post-render: syntax-highlight code blocks and add a header with the language
// label and a copy button. Runs on the live DOM after markdown is injected.
export function enhanceCodeBlocks(root: HTMLElement): void {
  root.querySelectorAll<HTMLPreElement>("pre").forEach((pre) => {
    if (pre.dataset.enhanced) return;
    const code = pre.querySelector("code");
    if (!code) return;
    pre.dataset.enhanced = "1";

    const cls = Array.from(code.classList).find((c) => c.startsWith("language-"));
    let lang = cls ? cls.slice(9) : "";
    const raw = code.textContent || "";
    try {
      if (lang && hljs.getLanguage(lang)) {
        code.innerHTML = hljs.highlight(raw, { language: lang }).value;
      } else {
        const res = hljs.highlightAuto(raw);
        code.innerHTML = res.value;
        lang = res.language || lang;
      }
      code.classList.add("hljs");
    } catch {
      /* leave code untouched if highlighting fails */
    }

    const wrap = document.createElement("div");
    wrap.className = "code-block";
    const head = document.createElement("div");
    head.className = "code-head";
    const label = document.createElement("span");
    label.className = "code-lang";
    label.textContent = lang || "text";
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "code-copy";
    btn.textContent = "Copy";
    btn.addEventListener("click", () => {
      navigator.clipboard?.writeText(raw).then(() => {
        btn.textContent = "Copied";
        setTimeout(() => (btn.textContent = "Copy"), 1400);
      });
    });
    head.append(label, btn);

    pre.parentNode?.insertBefore(wrap, pre);
    wrap.append(head, pre);
  });
}
